export interface CategoryOption {
  code: string
  name: string
}

export const BISAC_CATEGORIES: CategoryOption[] = [
  { code: 'ART000000', name: 'Art / General' },
  { code: 'BIO000000', name: 'Biography & Autobiography / General' },
  { code: 'BUS000000', name: 'Business & Economics / General' },
  { code: 'CGN000000', name: 'Comics & Graphic Novels / General' },
  { code: 'CKB000000', name: 'Cooking / General' },
  { code: 'COM000000', name: 'Computers / General' },
  { code: 'CRA000000', name: 'Crafts & Hobbies / General' },
  { code: 'DES000000', name: 'Design / General' },
  { code: 'EDU000000', name: 'Education / General' },
  { code: 'FAM000000', name: 'Family & Relationships / General' },
  { code: 'FIC000000', name: 'Fiction / General' },
  { code: 'FIC002000', name: 'Fiction / Action & Adventure' },
  { code: 'FIC004000', name: 'Fiction / Classics' },
  { code: 'FIC009000', name: 'Fiction / Fantasy / General' },
  { code: 'FIC014000', name: 'Fiction / Historical / General' },
  { code: 'FIC015000', name: 'Fiction / Horror' },
  { code: 'FIC016000', name: 'Fiction / Humorous / General' },
  { code: 'FIC019000', name: 'Fiction / Literary' },
  { code: 'FIC022000', name: 'Fiction / Mystery & Detective / General' },
  { code: 'FIC027000', name: 'Fiction / Romance / General' },
  { code: 'FIC028000', name: 'Fiction / Science Fiction / General' },
  { code: 'FIC031000', name: 'Fiction / Thrillers / General' },
  { code: 'GAR000000', name: 'Gardening / General' },
  { code: 'HEA000000', name: 'Health & Fitness / General' },
  { code: 'HIS000000', name: 'History / General' },
  { code: 'HOM000000', name: 'House & Home / General' },
  { code: 'HUM000000', name: 'Humor / General' },
  { code: 'JNF000000', name: 'Juvenile Nonfiction / General' },
  { code: 'JUV000000', name: 'Juvenile Fiction / General' },
  { code: 'LAN000000', name: 'Language Arts & Disciplines / General' },
  { code: 'LAW000000', name: 'Law / General' },
  { code: 'LCO000000', name: 'Literary Collections / General' },
  { code: 'MAT000000', name: 'Mathematics / General' },
  { code: 'MED000000', name: 'Medical / General' },
  { code: 'MUS000000', name: 'Music / General' },
  { code: 'NAT000000', name: 'Nature / General' },
  { code: 'OCC000000', name: 'Body, Mind & Spirit / General' },
  { code: 'PER000000', name: 'Performing Arts / General' },
  { code: 'PET000000', name: 'Pets / General' },
  { code: 'PHI000000', name: 'Philosophy / General' },
  { code: 'PHO000000', name: 'Photography / General' },
  { code: 'POE000000', name: 'Poetry / General' },
  { code: 'POL000000', name: 'Political Science / General' },
  { code: 'PSY000000', name: 'Psychology / General' },
  { code: 'REL000000', name: 'Religion / General' },
  { code: 'SCI000000', name: 'Science / General' },
  { code: 'SEL000000', name: 'Self-Help / General' },
  { code: 'SOC000000', name: 'Social Science / General' },
  { code: 'SPO000000', name: 'Sports & Recreation / General' },
  { code: 'TEC000000', name: 'Technology & Engineering / General' },
  { code: 'TRA000000', name: 'Transportation / General' },
  { code: 'TRV000000', name: 'Travel / General' },
  { code: 'YAF000000', name: 'Young Adult Fiction / General' },
  { code: 'YAN000000', name: 'Young Adult Nonfiction / General' },
]

export const KDC_CATEGORIES: CategoryOption[] = [
  { code: '000', name: '총류 (General)' },
  { code: '100', name: '철학 (Philosophy)' },
  { code: '200', name: '종교 (Religion)' },
  { code: '300', name: '사회과학 (Social Sciences)' },
  { code: '400', name: '자연과학 (Natural Sciences)' },
  { code: '500', name: '기술과학 (Technology)' },
  { code: '600', name: '예술 (Arts)' },
  { code: '700', name: '언어 (Language)' },
  { code: '800', name: '문학 (Literature)' },
  { code: '900', name: '역사 (History)' },
]
